language: c

compiler:
  - clang
  - gcc

script: 
  - cd libpam && ./bootstrap.sh && ./configure && make && make check
  - make super-clean && ./bootstrap.sh && ./configure --enable-config && make && make check

sudo: false

addons:
  apt:
    packages:
    - libpam0g-dev
    - libqrencode3
    - libconfig-dev
